using System;
using Unity.Mathematics;

namespace Appegy.Tessera
{
    /// <summary>
    ///     Finite jigsaw puzzle grid, 4-connected like <see cref="SquareGrid" />. Each
    ///     interior edge is a Draradech jigsaw silhouette (three cubic Beziers, 10
    ///     control points) generated by a deterministic per-edge RNG so adjacent
    ///     cells stitch exactly. Outer-frame edges are straight. The cell at
    ///     <c>(x, y)</c> has id <c>y * Width + x</c> and bounding rectangle
    ///     <c>[x*CellSize, (x+1)*CellSize] x [y*CellSize, (y+1)*CellSize]</c>. The
    ///     actual cell polygon extends past this rectangle wherever a tab pokes
    ///     into a neighbour, and pulls back wherever a neighbour pokes in.
    ///     Corner count is variable per cell: fully interior cells have
    ///     <c>4 + 4 * (SamplesPerEdge - 2)</c> corners; boundary cells have fewer
    ///     because the outer-frame edges contribute only their two endpoints.
    /// </summary>
    public sealed class ClassicPuzzleGrid : ITessellation
    {
        // CW side order: 0=right, 1=bottom, 2=left, 3=top.
        private static readonly int[] _sideDx = { +1, 0, -1, 0 };
        private static readonly int[] _sideDy = { 0, -1, 0, +1 };

        private readonly Bounds2 _bounds;
        // _vertEdges[y * (Width - 1) + x]: edge between (x, y) and (x+1, y).
        //   Stored from TR(x, y) = ((x+1)*S, (y+1)*S) to BR(x, y) = ((x+1)*S, y*S).
        private readonly float2[][] _vertEdges;
        // _horizEdges[y * Width + x]: edge between (x, y) and (x, y+1).
        //   Stored from TL(x, y) = (x*S, (y+1)*S) to TR(x, y) = ((x+1)*S, (y+1)*S).
        private readonly float2[][] _horizEdges;
        private readonly int _samplesPerEdge;
        private readonly int _interiorN;

        public ClassicPuzzleGrid(int width, int height, float cellSize, int seed)
            : this(width, height, cellSize, seed, ClassicPuzzleParameters.Default)
        {
        }

        public ClassicPuzzleGrid(int width, int height, float cellSize, int seed, ClassicPuzzleParameters parameters)
        {
            if (width <= 0) throw new ArgumentOutOfRangeException(nameof(width), "Width must be positive.");
            if (height <= 0) throw new ArgumentOutOfRangeException(nameof(height), "Height must be positive.");
            if (cellSize <= 0) throw new ArgumentOutOfRangeException(nameof(cellSize), "Cell size must be positive.");

            Width = width;
            Height = height;
            CellSize = cellSize;
            Seed = seed;
            Parameters = parameters;
            CellCount = width * height;
            _bounds = new Bounds2(float2.zero, new float2(width * cellSize, height * cellSize));
            _samplesPerEdge = parameters.SamplesPerEdge;
            _interiorN = _samplesPerEdge - 2;

            // Vertical interior edges: between (x, y) and (x+1, y) for x in [0, Width-2].
            // Walked TR(x, y) -> BR(x, y) (top to bottom).
            _vertEdges = new float2[(width - 1) * height][];
            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < width - 1; x++)
                {
                    var p0 = new float2((x + 1) * cellSize, (y + 1) * cellSize);
                    var p1 = new float2((x + 1) * cellSize, y * cellSize);
                    var poly = new float2[_samplesPerEdge];
                    var es = PuzzleEdgeSeed.Compute(seed, 0, x, y);
                    DraradechTab.Generate(p0, p1, es, parameters.TabSize, parameters.HeadMax, parameters.BezierSubdivisions, poly);
                    _vertEdges[y * (width - 1) + x] = poly;
                }
            }

            // Horizontal interior edges: between (x, y) and (x, y+1) for y in [0, Height-2].
            // Walked TL(x, y) -> TR(x, y) (left to right).
            _horizEdges = new float2[width * (height - 1)][];
            for (var y = 0; y < height - 1; y++)
            {
                for (var x = 0; x < width; x++)
                {
                    var p0 = new float2(x * cellSize, (y + 1) * cellSize);
                    var p1 = new float2((x + 1) * cellSize, (y + 1) * cellSize);
                    var poly = new float2[_samplesPerEdge];
                    var es = PuzzleEdgeSeed.Compute(seed, 1, x, y);
                    DraradechTab.Generate(p0, p1, es, parameters.TabSize, parameters.HeadMax, parameters.BezierSubdivisions, poly);
                    _horizEdges[y * width + x] = poly;
                }
            }
        }

        public int Width { get; }
        public int Height { get; }
        public float CellSize { get; }
        public int Seed { get; }
        public ClassicPuzzleParameters Parameters { get; }

        public int CellCount { get; }
        public Bounds2 Bounds => _bounds;

        /// <summary>Total polyline points per interior edge (constant across the grid). Boundary edges contribute only 2 points each.</summary>
        public int SamplesPerEdge => _samplesPerEdge;

        public int IdOf(int x, int y)
        {
            return y * Width + x;
        }

        public (int X, int Y) XYOf(int id)
        {
            return (id % Width, id / Width);
        }

        public float2 GetCenter(int id)
        {
            var (x, y) = XYOf(id);
            return new float2((x + 0.5f) * CellSize, (y + 0.5f) * CellSize);
        }

        public int GetCornersCount(int id)
        {
            var (x, y) = XYOf(id);
            return 4
                   + InteriorPointsOnSide(x, y, 0)
                   + InteriorPointsOnSide(x, y, 1)
                   + InteriorPointsOnSide(x, y, 2)
                   + InteriorPointsOnSide(x, y, 3);
        }

        public float2 GetCorner(int id, int cornerIndex)
        {
            var (cx, cy) = XYOf(id);
            var rCount = InteriorPointsOnSide(cx, cy, 0);
            var bCount = InteriorPointsOnSide(cx, cy, 1);
            var lCount = InteriorPointsOnSide(cx, cy, 2);
            var tCount = InteriorPointsOnSide(cx, cy, 3);
            var total = 4 + rCount + bCount + lCount + tCount;
            var idx = (cornerIndex % total + total) % total;

            // CW walk: TR, right interior, BR, bottom interior, BL, left interior, TL, top interior.
            if (idx == 0) return new float2((cx + 1) * CellSize, (cy + 1) * CellSize); // TR
            idx -= 1;
            if (idx < rCount)
            {
                // Right edge stored TR -> BR (forward).
                return _vertEdges[cy * (Width - 1) + cx][idx + 1];
            }
            idx -= rCount;
            if (idx == 0) return new float2((cx + 1) * CellSize, cy * CellSize); // BR
            idx -= 1;
            if (idx < bCount)
            {
                // Bottom edge of (cx, cy) is horiz at (cx, cy-1), stored TL -> TR.
                // CW traversal of cell goes BR -> BL, which is reverse of storage.
                var edge = _horizEdges[(cy - 1) * Width + cx];
                return edge[edge.Length - 2 - idx];
            }
            idx -= bCount;
            if (idx == 0) return new float2(cx * CellSize, cy * CellSize); // BL
            idx -= 1;
            if (idx < lCount)
            {
                // Left edge of (cx, cy) is vert at (cx-1, cy), stored TR -> BR (of cell cx-1).
                // CW traversal of (cx, cy) goes BL -> TL, which is reverse of storage.
                var edge = _vertEdges[cy * (Width - 1) + (cx - 1)];
                return edge[edge.Length - 2 - idx];
            }
            idx -= lCount;
            if (idx == 0) return new float2(cx * CellSize, (cy + 1) * CellSize); // TL
            idx -= 1;
            // Top edge of (cx, cy) is horiz at (cx, cy), stored TL -> TR (forward).
            return _horizEdges[cy * Width + cx][idx + 1];
        }

        public void CopyCorners(int id, Span<float2> dest)
        {
            var (cx, cy) = XYOf(id);
            var rCount = InteriorPointsOnSide(cx, cy, 0);
            var bCount = InteriorPointsOnSide(cx, cy, 1);
            var lCount = InteriorPointsOnSide(cx, cy, 2);
            var tCount = InteriorPointsOnSide(cx, cy, 3);
            var total = 4 + rCount + bCount + lCount + tCount;
            if (dest.Length < total)
            {
                throw new ArgumentException($"dest must have length >= {total}.", nameof(dest));
            }

            var k = 0;
            dest[k++] = new float2((cx + 1) * CellSize, (cy + 1) * CellSize); // TR
            if (rCount > 0)
            {
                var edge = _vertEdges[cy * (Width - 1) + cx];
                for (var i = 1; i <= rCount; i++) dest[k++] = edge[i];
            }
            dest[k++] = new float2((cx + 1) * CellSize, cy * CellSize); // BR
            if (bCount > 0)
            {
                var edge = _horizEdges[(cy - 1) * Width + cx];
                for (var i = edge.Length - 2; i >= 1; i--) dest[k++] = edge[i];
            }
            dest[k++] = new float2(cx * CellSize, cy * CellSize); // BL
            if (lCount > 0)
            {
                var edge = _vertEdges[cy * (Width - 1) + (cx - 1)];
                for (var i = edge.Length - 2; i >= 1; i--) dest[k++] = edge[i];
            }
            dest[k++] = new float2(cx * CellSize, (cy + 1) * CellSize); // TL
            if (tCount > 0)
            {
                var edge = _horizEdges[cy * Width + cx];
                for (var i = 1; i <= tCount; i++) dest[k++] = edge[i];
            }
        }

        /// <summary>
        ///     Number of polyline points on side <paramref name="side" /> of cell
        ///     <paramref name="id" /> including both endpoint corners. Side ordering
        ///     matches the neighbour ordering: 0 = right, 1 = bottom, 2 = left, 3 = top.
        /// </summary>
        public int GetSidePolylineLength(int id, int side)
        {
            var (x, y) = XYOf(id);
            var mod = (side % 4 + 4) % 4;
            return 2 + InteriorPointsOnSide(x, y, mod);
        }

        /// <summary>
        ///     Copies the polyline of side <paramref name="side" /> of cell
        ///     <paramref name="id" /> into <paramref name="dest" /> in clockwise
        ///     traversal direction (side 0 goes TR -> BR, side 1 goes BR -> BL, etc.).
        ///     Includes both endpoint corners. <paramref name="dest" />.Length must
        ///     be at least <see cref="GetSidePolylineLength" />.
        /// </summary>
        public void CopySidePolyline(int id, int side, Span<float2> dest)
        {
            var (cx, cy) = XYOf(id);
            var mod = (side % 4 + 4) % 4;
            var length = 2 + InteriorPointsOnSide(cx, cy, mod);
            if (dest.Length < length)
            {
                throw new ArgumentException($"dest must have length >= {length}.", nameof(dest));
            }

            switch (mod)
            {
                case 0:
                {
                    // Right: TR -> BR. Forward if interior, else just the two corners.
                    dest[0] = new float2((cx + 1) * CellSize, (cy + 1) * CellSize);
                    if (cx < Width - 1)
                    {
                        var edge = _vertEdges[cy * (Width - 1) + cx];
                        for (var i = 1; i < edge.Length; i++) dest[i] = edge[i];
                    }
                    else
                    {
                        dest[1] = new float2((cx + 1) * CellSize, cy * CellSize);
                    }
                    break;
                }
                case 1:
                {
                    // Bottom: BR -> BL. Reverse of horiz at (cx, cy-1) if interior.
                    dest[0] = new float2((cx + 1) * CellSize, cy * CellSize);
                    if (cy > 0)
                    {
                        var edge = _horizEdges[(cy - 1) * Width + cx];
                        var n = edge.Length;
                        for (var i = 1; i < n; i++) dest[i] = edge[n - 1 - i];
                    }
                    else
                    {
                        dest[1] = new float2(cx * CellSize, cy * CellSize);
                    }
                    break;
                }
                case 2:
                {
                    // Left: BL -> TL. Reverse of vert at (cx-1, cy) if interior.
                    dest[0] = new float2(cx * CellSize, cy * CellSize);
                    if (cx > 0)
                    {
                        var edge = _vertEdges[cy * (Width - 1) + (cx - 1)];
                        var n = edge.Length;
                        for (var i = 1; i < n; i++) dest[i] = edge[n - 1 - i];
                    }
                    else
                    {
                        dest[1] = new float2(cx * CellSize, (cy + 1) * CellSize);
                    }
                    break;
                }
                case 3:
                {
                    // Top: TL -> TR. Forward if interior.
                    dest[0] = new float2(cx * CellSize, (cy + 1) * CellSize);
                    if (cy < Height - 1)
                    {
                        var edge = _horizEdges[cy * Width + cx];
                        for (var i = 1; i < edge.Length; i++) dest[i] = edge[i];
                    }
                    else
                    {
                        dest[1] = new float2((cx + 1) * CellSize, (cy + 1) * CellSize);
                    }
                    break;
                }
            }
        }

        public int GetCellAt(float2 point)
        {
            if (!_bounds.Contains(point)) return -1;
            var rx = (int)math.floor(point.x / CellSize);
            var ry = (int)math.floor(point.y / CellSize);
            rx = math.clamp(rx, 0, Width - 1);
            ry = math.clamp(ry, 0, Height - 1);

            // The point belongs to either the rectangle cell or one of its 4 axis
            // neighbours: a tab can reach at most HeadMax * CellSize < 0.5 * CellSize
            // perpendicular to the edge, never deeper than one cell width.
            if (PointInCell(point, rx, ry)) return IdOf(rx, ry);
            for (var side = 0; side < 4; side++)
            {
                var nx = rx + _sideDx[side];
                var ny = ry + _sideDy[side];
                if (nx < 0 || nx >= Width || ny < 0 || ny >= Height) continue;
                if (PointInCell(point, nx, ny)) return IdOf(nx, ny);
            }
            // Fallback for floating-point edge cases right on a polyline.
            return IdOf(rx, ry);
        }

        public int GetNeighborCount(int id)
        {
            return 4;
        }

        public int GetNeighbor(int id, int neighborIndex)
        {
            var (x, y) = XYOf(id);
            var idx = (neighborIndex % 4 + 4) % 4;
            var nx = x + _sideDx[idx];
            var ny = y + _sideDy[idx];
            if (nx < 0 || nx >= Width || ny < 0 || ny >= Height) return -1;
            return IdOf(nx, ny);
        }

        public bool AreNeighbors(int a, int b)
        {
            if (a == b) return false;
            if (a < 0 || a >= CellCount || b < 0 || b >= CellCount) return false;
            var (ax, ay) = XYOf(a);
            var (bx, by) = XYOf(b);
            return Math.Abs(ax - bx) + Math.Abs(ay - by) == 1;
        }

        public int GetNeighborIndex(int cell, int neighbor)
        {
            if (cell == neighbor) return -1;
            if (cell < 0 || cell >= CellCount || neighbor < 0 || neighbor >= CellCount) return -1;
            var (cx, cy) = XYOf(cell);
            var (nx, ny) = XYOf(neighbor);
            var dx = nx - cx;
            var dy = ny - cy;
            if (dx == 1 && dy == 0) return 0;
            if (dx == 0 && dy == -1) return 1;
            if (dx == -1 && dy == 0) return 2;
            if (dx == 0 && dy == 1) return 3;
            return -1;
        }

        public int Distance(int a, int b)
        {
            var (ax, ay) = XYOf(a);
            var (bx, by) = XYOf(b);
            return Math.Abs(ax - bx) + Math.Abs(ay - by);
        }

        private int InteriorPointsOnSide(int x, int y, int side)
        {
            return side switch
            {
                0 => x < Width - 1 ? _interiorN : 0,
                1 => y > 0 ? _interiorN : 0,
                2 => x > 0 ? _interiorN : 0,
                3 => y < Height - 1 ? _interiorN : 0,
                _ => 0,
            };
        }

        private bool PointInCell(float2 p, int cx, int cy)
        {
            var id = IdOf(cx, cy);
            var count = GetCornersCount(id);
            var poly = new float2[count];
            CopyCorners(id, poly);
            // Ray-casting point-in-polygon (horizontal ray to +infinity from p).
            var inside = false;
            for (int i = 0, jPrev = count - 1; i < count; jPrev = i++)
            {
                var ci = poly[i];
                var cj = poly[jPrev];
                if (ci.y > p.y != cj.y > p.y)
                {
                    var xCross = ci.x + (p.y - ci.y) / (cj.y - ci.y) * (cj.x - ci.x);
                    if (p.x < xCross) inside = !inside;
                }
            }
            return inside;
        }
    }
}
